Attempt to update to latest biny and newer gradle, loom, and mod versions
mineLdiver/smoothbeta pull request #5
Opened 2024-12-28 02:05 UTC by telvarost

For some reason the blocks aren't rendering. This was my attempt. The mod is broken on StationAPI alpha.3 so I thought I would try to attempt to migrate the mod to it, but I couldn't event get it to work on alpha.2.4 in the dev environment

2024-12-28 03:11 UTC, telvarost commented
PR is ready. I finished the migration to StationAPI alpha.3

2025-01-07 07:01 UTC, mineLdiver requested changes
A few nitpicks

2025-01-07 07:01 UTC, mineLdiver commented on build.gradle
> +	implementation("io.github.llamalad7:mixinextras-fabric:${project.properties["mixinextras_version"]}")
Why is MixinExtras added?

2025-01-07 07:01 UTC, mineLdiver commented on gradle.properties
> +mixinextras_version = 0.2.1
Same here.

2025-01-07 07:01 UTC, mineLdiver commented on gradle.properties
> +mod_version=1.2.0
1.1.6 is more fitting I say, no new features were introduced.

2025-01-07 07:01 UTC, mineLdiver commented on build.gradle
>  //	}
GN and GCAPI added but AMI commented out?

2025-01-07 13:19 UTC, telvarost commented on build.gradle
> +	implementation("io.github.llamalad7:mixinextras-fabric:${project.properties["mixinextras_version"]}")
This was something I used to do before it became a part of our loader/babric in general. I've begun removing it from all of my mods. An oversight on my part. Removed. :+1:

2025-01-07 13:20 UTC, telvarost commented on gradle.properties
> +mixinextras_version = 0.2.1
Good catch. Removed

2025-01-07 13:20 UTC, telvarost commented on gradle.properties
> +mod_version=1.2.0
Fixed

2025-01-07 13:21 UTC, telvarost commented on build.gradle
>  //	}
I'm honestly not sure. Maybe AMI wasn't updated at the time? Anyways, the AMI version has been updated and it has been uncommented. If you'd like me to remove AMI, GN, or GCAPI just let me know and I can do so.

2025-01-07 15:28 UTC, mineLdiver approved these changes

2025-01-07 15:28 UTC, merged